#ifndef PRACTICECOPY_PRINTEMPLOYERINFO_H
#define PRACTICECOPY_PRINTEMPLOYERINFO_H
#include <iostream>
#include <fstream>
#include <iomanip>
#include "../Employer.h"
#include "GetCountOfEmployers.h"
#include "GetArrayOfEmployers.h"
void printEmployerInfo();
#endif //PRACTICECOPY_PRINTEMPLOYERINFO_H
